# Generated by Django 3.2 on 2023-07-26 22:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('store', '0004_product_seller'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='seller',
        ),
        migrations.AddField(
            model_name='product',
            name='visibility',
            field=models.IntegerField(choices=[(0, 'not visible'), (1, 'Searchable'), (2, 'Listed'), (3, 'Always Visible')], db_index=True, default=3, help_text='Choose how you want your product to be seen and found by the customers. <p>Not visible: Product will not be shown in your store front nor found in search.</p><p>Searchable: Product will be shown in search, but not listed on any category page.</p><p>Listed: Product will be shown on category pages, but not shown in search results.</p><p>Always Visible: Product will be shown in your store front and found in search.</p>', verbose_name='visibility'),
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255, null=True)),
                ('city', models.CharField(max_length=255, null=True)),
                ('district', models.CharField(max_length=255, null=True)),
                ('phone_number', models.CharField(max_length=50)),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='created on')),
                ('modified_on', models.DateTimeField(auto_now=True, db_index=True, verbose_name='modified on')),
                ('domain', models.CharField(blank=True, help_text='Your shop domain name. Use this field to configure the URL that is used to visit your store front. Note: this requires additional configuration through your internet domain registrar.', max_length=128, null=True, unique=True, verbose_name='domain')),
                ('status', models.IntegerField(choices=[(0, 'disabled'), (1, 'enabled')], default=0, help_text="Your shop's status. Disable your shop if it's no longer in use. For temporary closing enable the maintenance mode, available in the `Maintenance Mode` tab on the left.", verbose_name='status')),
                ('prices_include_tax', models.BooleanField(default=True, help_text='This option defines whether product prices entered in admin include taxes. Note: this behavior can be overridden with contact group pricing.', verbose_name='prices include tax')),
                ('username', models.CharField(blank=True, max_length=50, unique=True)),
                ('store_name', models.CharField(max_length=50, null=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('licence_id', models.CharField(blank=True, max_length=25, null=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('favicon', filer.fields.image.FilerImageField(blank=True, help_text="Shop's favicon - a mini-image graphically representing your shop. Depending on the browser, it will be shown next to the address bar and/or on the website title tab.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shop_favicons', to=settings.FILER_IMAGE_MODEL, verbose_name='favicon')),
                ('logo', filer.fields.image.FilerImageField(blank=True, help_text="Shop's logo. Will be shown at theme.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shop_logos', to=settings.FILER_IMAGE_MODEL, verbose_name='logo')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='product',
            name='vendor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='store.vendor'),
            preserve_default=False,
        ),
    ]
