# Generated by Django 3.2 on 2023-07-27 10:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20230727_0510'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='is_approved',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='licence_id',
        ),
        migrations.AddField(
            model_name='vendor',
            name='commission_rate',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
        ),
    ]
