# Generated by Django 3.2 on 2023-08-09 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0002_auto_20230807_1847'),
        ('store', '0007_auto_20230807_1640'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='vendor',
        ),
        migrations.AddField(
            model_name='product',
            name='vendors',
            field=models.ManyToManyField(related_name='products', to='vendors.Vendor'),
        ),
    ]
