version: '3'

services:
  db:
    image: postgres
    ports:
      - '11432:5432'
    networks:
      - 9healthnetwork
    environment:
<<<<<<< Updated upstream
      - POSTGRES_DB=${DB_USERNAME}
      - POSTGRES_USER=${DB_PASSWORD}
      - POSTGRES_PASSWORD=${DB_NAME}
  web:
=======
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=greatkart
  9health_ecom:
>>>>>>> Stashed changes
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    networks:
      - 9healthnetwork
    environment:
      - POSTGRES_NAME=${DB_NAME}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    depends_on:
      - db
    links:
      - db:db

networks:
  9healthnetwork:
    driver: bridge
