# Generated by Django 3.2 on 2023-08-07 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0001_initial'),
        ('orders', '0002_orderproduct_vendor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderproduct',
            name='vendor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vendors.vendor'),
        ),
    ]
