# Generated by Django 3.2 on 2023-08-20 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_shipping_address'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ShippingMethod',
            new_name='ShippingVendor',
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('P', 'paypal'), ('M', 'momo'), ('C', 'cod')], max_length=1),
        ),
    ]
