# Generated by Django 3.2 on 2023-08-26 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20230820_2127'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='order_payment',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='payment_order', to='orders.order'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('PENDING', 'pending'), ('COMPLETED', 'completed'), ('FAILED', 'failed')], max_length=100),
        ),
    ]
