# Generated by Django 3.2 on 2023-09-05 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_alter_payment_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='order_payment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_id', to='orders.order'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('P', 'paypal'), ('M', 'momo'), ('C', 'cod')], default='M', max_length=1),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('PENDING', 'pending'), ('COMPLETED', 'completed'), ('FAILED', 'failed')], default='PENDING', max_length=100),
        ),
    ]
